
- hosts: servers
  gather_facts: True
  vars_files:
      - vars.yml

  #
  # Tasks
  #

  tasks:

      - name: Show ansible version
        debug:
            msg: "ansible_version: {{ansible_version.major}}"

      - name: Check ansible version
        fail:
            msg: "This playbook requires Ansible 2.x or greater."
        when: ansible_version.major < 2

      #
      # Server setup
      #

      - name: Install locale
        become: true
        #become_user: root
        template:
            src: provisioning/locale
            dest: /etc/default/locale

      - name: Set locale
        become: true
        #become_user: root
        locale_gen:
            name: "{{locale}}"
            state: present

      - name: Install required packages.
        become: true
        apt:
            pkg: "{{system_packages}}"
            state: present
            update_cache: "{{apt_update_cache}}"

      #
      # Nginx
      #

      - name: Ensure packages required by Nginx are installed
        become: true
        apt:
            pkg: ['build-essential', 'nginx']
            state: present

      - name: Install Nginx config file
        become: true
        template:
            src: provisioning/nginx.conf
            dest: /etc/nginx/nginx.conf
        notify:
            Restart Nginx

      - name: Remove default nginx site
        become: true
        file:
            path: /etc/nginx/sites-enabled/default
            state: absent
        notify:
          - Restart Nginx

      #
      # Redis
      #

      - name: Ensure packages required by Redis-server are installed
        become: true
        apt:
            pkg: ['redis-server']
            state: present

      - name: Disable Redis "Save the DB on disk"
        become: true
        blockinfile:
          path: /etc/redis/redis.conf
          insertafter: EOF
          block: |
            # Disable Save the DB on disk
            save ""
        notify:
            Restart Redis

      # TODO: verificare
      # - name: Install Redis config file
      #   become: true
      #   template:
      #       src: provisioning/redis.conf
      #       dest: /etc/redis/redis.conf
      #   notify:
      #       Restart Redis

      #
      # Supervisor
      #

      - name: Ensure packages required by Supervisor are installed
        become: true
        apt:
            pkg: ['supervisor']
            state: present

      # - name: Add inet_http_server section to main Supervisor config file
      #   become: true
      #   blockinfile:
      #     path: /etc/supervisor/supervisord.conf
      #     block: |
      #       [inet_http_server]
      #       #port = *:9001
      #       port = 127.0.0.1:9001
      #       #username = user
      #       #password = 123

  #
  # Handlers
  #

  handlers:

      - name: Restart Nginx
        become: true
        service:
            name: nginx
            state: restarted

      - name: Reload Nginx
        become: true
        service:
            name: nginx
            state: reloaded

      - name: Restart Redis
        become: true
        service:
            name: redis-server
            state: restarted
